pipeline:
  name: Test_pipeline
  identifier: Test_pipeline
  projectIdentifier: Sample_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Test_connector
        repoName: test
        build: <+input>
  stages:
    - stage:
        name: Run
        identifier: Run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "welcome"
                  description: test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: pendyalarohithp/test_docker
                    tags: <+input>
                    caching: false
